name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        sudo apt install zip jq -y
    - name: build 
      run: |
        cd ./soft/t_u_REV/
        pio run
    - name: firmware_builds
      uses: actions/upload-artifact@v2
      with:
        name: firmwares
        path: ./soft/t_u_REV/.pio/build/*/firmware.hex